using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WishlistApi.Migrations
{
    /// <inheritdoc />
    public partial class AddUserRelationships : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Use raw SQL to conditionally add columns and tables
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='wishlists' AND column_name='user_id') THEN
                        ALTER TABLE wishlists ADD COLUMN user_id integer NOT NULL DEFAULT 0;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='products' AND column_name='month') THEN
                        ALTER TABLE products ADD COLUMN month text NOT NULL DEFAULT '';
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='products' AND column_name='user_id') THEN
                        ALTER TABLE products ADD COLUMN user_id integer NOT NULL DEFAULT 0;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS users (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email text NOT NULL,
                    password_hash text NOT NULL,
                    created_at timestamp with time zone NOT NULL
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_wishlists_user_id"" ON wishlists (user_id);");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_products_user_id"" ON products (user_id);");

            // Create a default user if there are any products or wishlists with user_id = 0
            migrationBuilder.Sql(@"
                DO $$
                DECLARE
                    default_user_id integer;
                BEGIN
                    -- Check if there are any products or wishlists with user_id = 0
                    IF EXISTS (SELECT 1 FROM products WHERE user_id = 0) OR 
                       EXISTS (SELECT 1 FROM wishlists WHERE user_id = 0) THEN
                        
                        -- Create a default user if it doesn't exist
                        INSERT INTO users (email, password_hash, created_at)
                        VALUES ('default@example.com', 'placeholder_hash', NOW())
                        ON CONFLICT DO NOTHING
                        RETURNING id INTO default_user_id;
                        
                        -- If user already exists, get its id
                        IF default_user_id IS NULL THEN
                            SELECT id INTO default_user_id FROM users WHERE email = 'default@example.com';
                        END IF;
                        
                        -- Update products with user_id = 0 to use the default user
                        UPDATE products SET user_id = default_user_id WHERE user_id = 0;
                        
                        -- Update wishlists with user_id = 0 to use the default user
                        UPDATE wishlists SET user_id = default_user_id WHERE user_id = 0;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_products_users_user_id') THEN
                        ALTER TABLE products ADD CONSTRAINT ""FK_products_users_user_id"" 
                        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_wishlists_users_user_id') THEN
                        ALTER TABLE wishlists ADD CONSTRAINT ""FK_wishlists_users_user_id"" 
                        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_products_users_user_id",
                table: "products");

            migrationBuilder.DropForeignKey(
                name: "FK_wishlists_users_user_id",
                table: "wishlists");

            migrationBuilder.DropTable(
                name: "users");

            migrationBuilder.DropIndex(
                name: "IX_wishlists_user_id",
                table: "wishlists");

            migrationBuilder.DropIndex(
                name: "IX_products_user_id",
                table: "products");

            migrationBuilder.DropColumn(
                name: "user_id",
                table: "wishlists");

            migrationBuilder.DropColumn(
                name: "month",
                table: "products");

            migrationBuilder.DropColumn(
                name: "user_id",
                table: "products");
        }
    }
}
