-- Manual migration script to add user relationships
-- Run this if automatic migration fails due to existing columns

-- Check and add user_id to wishlists if not exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='wishlists' AND column_name='user_id') THEN
        ALTER TABLE wishlists ADD COLUMN user_id integer NOT NULL DEFAULT 0;
    END IF;
END $$;

-- Check and add month to products if not exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='products' AND column_name='month') THEN
        ALTER TABLE products ADD COLUMN month text NOT NULL DEFAULT '';
    END IF;
END $$;

-- Check and add user_id to products if not exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='products' AND column_name='user_id') THEN
        ALTER TABLE products ADD COLUMN user_id integer NOT NULL DEFAULT 0;
    END IF;
END $$;

-- Check and create users table if not exists
CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    password_hash text NOT NULL,
    created_at timestamp with time zone NOT NULL
);

-- Create indexes if they don't exist
CREATE INDEX IF NOT EXISTS "IX_wishlists_user_id" ON wishlists (user_id);
CREATE INDEX IF NOT EXISTS "IX_products_user_id" ON products (user_id);

-- Add foreign keys if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_products_users_user_id') THEN
        ALTER TABLE products ADD CONSTRAINT "FK_products_users_user_id" 
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_wishlists_users_user_id') THEN
        ALTER TABLE wishlists ADD CONSTRAINT "FK_wishlists_users_user_id" 
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
END $$;
